apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegen
  namespace: photo-styling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagegen
  template:
    metadata:
      labels:
        app: imagegen
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: g2-gpu-rtx4000a2-m
      containers:
        - name: imagegen-predictor
          image: ${DOCKERHUB_USER}/imagegen-predictor:latest
          ports:
            - containerPort: 8080
          env:
            - name: IMAGEGEN_MODEL_NAME
              value: black-forest-labs/FLUX.1-schnell
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
          resources:
            requests:
              memory: "32Gi"
              nvidia.com/gpu: "2"
            limits:
              memory: "48Gi"
              nvidia.com/gpu: "2"
